### ISSUE TITLE
Cannot push or pull Gravity Databases

### ISSUE THREAD

**Issue by Coliinnn** [vmstan/gravity-sync#346]
**Issue Description**
I am trying to install Gravity Sync on my two pihole instances. The installation went fine (although I manually had to copy over the SSH keys to the other peer), but `gravity-sync push` or `gravity-sync pull` both result in the following: `✗ Pulling the remote Gravity Database` / `✗ Pushing the local Gravity Database`.

**Configuration Details**
- The main instance is running in Docker, which in turn is running in a Proxmox LXC container.
- The secondary instance is running on a Raspberry Pi 4B, also inside Docker. Both use the official Docker image.
- Gravity-Sync is installed on the hosts, not in the Docker containers
- Pihole is running on both servers
- Docker-compose.yml: This compose also contains the full internal IP address before the ports because I ran into some other issue with the pihole install (it is set like this only on the LXC container, not on the Raspberry Pi).
```
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.04.3
    ports:
    - "8089:80/tcp"
    - "10.17.7.21:53:53/tcp"
    - "10.17.7.21:53:53/udp"
    - "67:67/udp"
    environment:
    - INTERFACE=eth0
    volumes:
    - type: bind
      source: ./volumes/pihole/etc-pihole
      target: /etc/pihole
    - type: bind
      source: ./volumes/pihole/etc-dnsmasq.d
      target: /etc/dnsmasq.d
   # volumes:
   # - ./volumes/pihole/etc-pihole:/etc/pihole
   # - ./volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
```

**Things I tried**
- `gravity-sync compare` seems to work fine, and is able to detect the remote pihole instances
- Pushing from the main pihole to the secondary
- Pulling from the main to the secondary
- Pushing from the secondary to the main
- Pulling from the secondary to the main (all of the above result in the same error)
- I _can_ SSH from one host to another and vice-versa
- The `/etc/gravity-sync/gravity-sync.rsa` and `/etc/gravity-sync/gravity-sync.rsa.pub` are both owned by the right user and group (colin:colin on the main, pi:pi on the secondary)
- Made sure that the configuration contains the right user+IP combination for the peers
- Removed the installation on both servers, rebooted, re-installed on both servers, rebooted, configured on both servers
- Made sure that the servers fulfil the requirements for Gravity Sync
- Explicitly making bindmounts in docker-compose.yml on both servers

**Full Logs**
```
∞ Initializing Gravity Sync (4.0.4)
✓ Loading gravity-sync.conf
✓ Detecting local Pi-hole installation
✓ Detecting remote Pi-hole installation
✓ Gravity Sync remote peer is configured
✓ Evaluating arguments: PUSH
» Remote target pi@10.17.7.12
✓ Validating pathways to Pi-hole
✓ Validating pathways to DNSMASQ
∞ Hashing the remote Gravity Databasemd5sum: /etc/pihole/gravity.db: No such file or directory
✓ Hashing the remote Gravity Database
✓ Comparing to the local Gravity Database
! Differences detected in the Gravity Database
! DNS Records not detected on the remote Pi-hole
! DNS CNAMEs not detected on the local Pi-hole
! Static DHCP Addresses not detected on the local Pi-hole
! Replication of Pi-hole settings is required
✓ Performing backup of remote Gravity Database
✓ Performing backup of local Gravity Database
✓ Checking Gravity Database copy integrity
✗ Pushing the local Gravity Database
```

I hope this provides sufficient information to debug this. I don't know what further to try, as I also cannot find a way to get more verbose debugging. Any help would be appreciated.
