### ISSUE TITLE
Error when running 'gravity-sync auto'

### ISSUE THREAD

**Issue by imamouse111** [vmstan/gravity-sync#444]
Looking for advice on how to get 'gravity-sync auto' to work in Pihole Docker instance. I can get 'gravity-sync push' to work but 'auto' throws back 'System has not been booted with systemd as init system (PID 1). Can't operate.' And that's after I've already installed systemd.

### Here's my basic setup:

Pihole Docker (Openmediavault (Portainer (Pihole + macvlan))) = Primary 192.168.86.222
Pihole Raspi (bare metal) = Secondary 192.168.86.154

### Here is my Docker Compose YAML:

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 55:53/tcp
      - 55:53/udp
      - 67:67/udp
      - 83:80/tcp
    environment:
      - TZ:$TZ
      - WEBPASSWORD:$PW
      - DNSSEC=true
    volumes:
      - $DATA/pihole/config/etc-pihole:/etc/pihole
      - $DATA/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: "192.168.86.222"
```

I'm able to install Gravity Sync on the raspi pretty easily using [this guide](https://geekscircuit.com/sync-pi-hole-dockers/), but installing in the Docker Pihole requires a whole process that involves doing a 'docker exec' into the container and installing the OpenSSH client and systemd, but it eventually worked. I got Gravity Sync to successfully install but I don't want to have to re-do this process everytime I restart the container (suggestions on how to avoid this are welcome).

Per the above guide, I was able to modify the gravity-sync.conf files on each instance as below. I'm not totally confident I've done everything correctly, so these honestly might be my main issue.

### Raspi Pihole gravity-sync.conf:
```
# REQUIRED SETTINGS ##########################

REMOTE_HOST='192.168.86.154'
REMOTE_USER='pi'

# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
 LOCAL_PIHOLE_DIRECTORY='/etc/pihole'                       # Local Pi-hole data directory
 REMOTE_PIHOLE_DIRECTORY='/etc/pihole'                      # Remote Pi-hole data directory
 LOCAL_DNSMASQ_DIRECTORY='/etc/dnsmasq.d'                # Local DNSMASQ/FTL data directory
 REMOTE_DNSMASQ_DIRECTORY='/etc/dnsmasq.d'               # Remote DNSMASQ/FTL data directory
 LOCAL_FILE_OWNER='999:999'                       # Local file owner for Pi-hole
 REMOTE_FILE_OWNER='999:999'                      # Remote file owner for Pi-hole

# Pi-hole Docker/Podman container name - Docker will pattern match anything set below
# LOCAL_DOCKER_CONTAINER=''                                 # Local Pi-hole container name
 REMOTE_DOCKER_CONTAINER='pihole'                               # Remote Pi-hole container name

# HIDDEN FIGURES #############################
# See https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures
```

### Docker Pihole gravity-sync.conf:
```
# REQUIRED SETTINGS ##########################

REMOTE_HOST='192.168.86.222'
REMOTE_USER='root'    #Using 'root' because no 'pi' user is detected when I 'id pi'

# CUSTOM VARIABLES ###########################

# Pi-hole Folder/File Customization - Only need to be customized when using containers
 LOCAL_PIHOLE_DIRECTORY='/etc/pihole'                       # Local Pi-hole data directory
 REMOTE_PIHOLE_DIRECTORY='/etc/pihole'                      # Remote Pi-hole data directory
 LOCAL_DNSMASQ_DIRECTORY='/etc/dnsmasq.d'                # Local DNSMASQ/FTL data directory
 REMOTE_DNSMASQ_DIRECTORY='/etc/dnsmasq.d'               # Remote DNSMASQ/FTL data directory
 LOCAL_FILE_OWNER='999:999'                       # Local file owner for Pi-hole
 REMOTE_FILE_OWNER='999:999'                      # Remote file owner for Pi-hole

# Pi-hole Docker/Podman container name - Docker will pattern match anything set below
 LOCAL_DOCKER_CONTAINER='pihole'                                 # Local Pi-hole container name
#REMOTE_DOCKER_CONTAINER=''                               # Remote Pi-hole container name

# HIDDEN FIGURES #############################
# See https://github.com/vmstan/gravity-sync/wiki/Hidden-Figures
```

If someone can share how they were able to get this to work or point out what I'm doing wrong, I would be eternally grateful. Thanks in advance =)
